### ISSUE TITLE
Equipped item actions request

### ISSUE THREAD

**Issue by ArtificialPB** [Strikeskids/CacheReader#11]
Would it be possible to get actions of item when it's equipped?

**Comment by Strikeskids** [comment]
You can find those in the item information (idx 249) https://gist.github.com/Strikeskids/8271502. They are indices 528, 529, 530, 531, 1211

**Comment by Strikeskids** [comment]
1fe6f29e2c48e7860754be75c397cf9b3f95f67e Added :)

**Comment by ArtificialPB** [comment]
Awesome! Thanks man, I really appreciate it! :)
