### ISSUE TITLE
OSRS Region loader

### ISSUE THREAD

**Issue by ArtificialPB** [Strikeskids/CacheReader#12]
Is there any way you could add OSRS region loader? I can provide you classes for loading and decoding npcs, objects, items and scripts. I'm trying to add it my self but I have some trouble with decoding region data.

.

**Comment by Strikeskids** [comment]
You can't do region data because it's encrypted by XTEA keys.

**Comment by ArtificialPB** [comment]
Never mind then, was not aware of that.
