### ISSUE TITLE
RegionDataLoader load fails

### ISSUE THREAD

**Issue by Logicail** [Strikeskids/CacheReader#8]
Line 24 missing "!" should be
```
if (!RegionUtil.validateRegionCoordinates(regionX, regionY)) {
```

I haven't made a pull request because I'm not sure if validateRegionCoordinates should also be updated to check ```&& regionY <= REGION_MASK```

**Comment by Strikeskids** [comment]
Fixed. See commit 2476e28edc2326eeb7e4eeaf011b1ab765942760
